export enum ActionEnum {
	UPDATE_BOARD = 'UPDATE_BOARD',
	UPDATE_BOARD_1P = 'UPDATE_BOARD_1P',
	UPDATE_PLAYER = 'UPDATE_PLAYER',
	CHECK_ENDGAME = 'CHECK_ENDGAME',
	UPDATE_PLAYER_NUMBER = 'UPDATE_PLAYER_NUMBER',
	COMPUTER_PLAYING = 'COMPUTER_PLAYING',
	RESET = 'RESET'
}
