export enum ActionEnum {
	PLAYER_UPDATE_BOARD = 'PLAYER_UPDATE_BOARD',
	COMPUTER_UPDATE_BOARD = 'COMPUTER_UPDATE_BOARD',
	CHANGE_PLAYER = 'CHANGE_PLAYER',
	CHECK_ENDGAME = 'CHECK_ENDGAME',
	UPDATE_PLAYER_NUMBER = 'UPDATE_PLAYER_NUMBER',
	RESET = 'RESET',
	UPDATE_SCORE = 'UPDATE_SCORE'
}
